### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [sheredom/utf8.h#1]
I would like to point out that an identifier like "[`__UTF8_H__`](https://github.com/sheredom/utf8.h/blob/489e433e7d2c8a24978e8cfc6675a4e21970ff86/utf8.h#L26)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by sheredom** [comment]
Fixed in the same way as your json.h bug!

**Comment by elfring** [comment]
Thanks for [your improvement of an affected include guard](https://github.com/sheredom/utf8.h/commit/377c3c7b792b6ffc19f4f7ab31e06ee3944cf9b7 "Renaming of an include guard").
