### ISSUE TITLE
int might be too small for a code point

### ISSUE THREAD

**Issue by fluks** [sheredom/utf8.h#10]
`utf8chr` uses an `int` type, which can be 16 bits wide, for `chr` code point argument. Maximum code point is 0x10FFFF which is more than 16 bits. To be more portable, `chr` argument's type should be something that is always large enough, maybe `long` if you don't want to include `stdint.h`.

**Comment by sheredom** [comment]
Good catch! I'll rework :)

**Comment by sheredom** [comment]
https://github.com/sheredom/utf8.h/pull/11 is testing the fix for this now!

**Comment by Gumichan01** [comment]
@sheredom : I don't really know why your fix did not pass the travis tests. I have made another fix that seems identical with yours and it passed all of the tests. I created a new pull request #15 for that

**Comment by sheredom** [comment]
@Gumichan01 Thanks a ton - your MR did indeed work a charm and I can close this issue :smile:
