### ISSUE TITLE
[Documentation] taglib needs a utf8.h file - is this file here the right one?

### ISSUE THREAD

**Issue by rubyFeedback** [sheredom/utf8.h#125]
Today I wanted to compile a fresh git clone checkout from taglib:

    /home/x/Temp/rbt/taglib-08.07.2024/taglib/toolkit/tstring.cpp:31:10: fatal error: utf8.h: No such file or directory
     31 | #include <utf8.h>
     | ^~~~~~~~
    compilation terminated.

taglib wants some header called utf8.h.

Is the project here the right one?

Would it be possible to mention this on the main README?

Right now I am not entirely certain how utf8.h plays into this. Perhaps it is a totally unrelated project,
I really don't know. I did not write any of the code so I am not sure if I need this utf8.h or not.

Could the main README explain the use cases of utf8.h here on a modern linux system? In particular
if you know whether some projects need it or not. taglib is not the only one that suddenly asks for
utf8.h. At first I thought this comes from glibc, but now I am not sure, which is why any improvement
to the main README would be so useful, to know whether I am on the wrong track. (My binutils is
acting weirdly too, almost as if it assumes I use BSD rather than linux; not sure if this is involved here
or not.)

**Comment by sheredom** [comment]
I have no idea what taglib is - but you should go talk to them!
