### ISSUE TITLE
More readible/maintainable tests

### ISSUE THREAD

**Issue by MattSturgeon** [sheredom/utf8.h#17]
Hi

I was just looking through tests/main.c and I noticed that all the error codes are hard coded into the test functions themselves.

I'm not sure what the reason is for this, but my initial thought was that it would be better to have a header file define an enum that could contain descriptive error codes for all the functions.

Tedious and boring work, I know, but would make it easier to add new error codes and to reason about each test - assuming this wouldn't break something that relies on knowing the codes without being able to read an enum...

**Comment by sheredom** [comment]
Totally agreed - I've been meaning to port it over to using my other single header unit test lib (see https://github.com/sheredom/utest.h). I'll do a merge request for this ASAP.
