### ISSUE TITLE
tolower and toupper?

### ISSUE THREAD

**Issue by angelog** [sheredom/utf8.h#25]
How does this work with utf8?

I can use `tolower()` and `toupper()` to get lowercase or uppercase characters of ascii chars, but there's nothing in this library for converting codepoints, from what I see.

**Comment by sheredom** [comment]
So @angelog do you basically want utf8 variants of `tolower()` and `toupper()`, from the <ctype.h> header? Any of the other functions useful too?

**Comment by angelog** [comment]
Hm, not sure about other functions, but those are a few I particularly need. Perhaps functions like `isupper`, `islower` too.

**Comment by angelog** [comment]
I looked into this a bit, seems like it'll be difficult to support it _properly_. With that I mean, apparently things like `ß` in uppercase is `SS` and there's a lot more edge cases like that.

What a `toupper` and `tolower` could do as a bare minimum is handle ascii upper and lower case, but handling every usecase probably isn't maintainable.

**Comment by sheredom** [comment]
Thanks!
