### ISSUE TITLE
Procedure for adding a single codepoint to an existing string

### ISSUE THREAD

**Issue by angelog** [sheredom/utf8.h#26]
It'd be nice to have a function for this. Perhaps a function that returns how many bytes a codepoint needs would be enough.

**Comment by sheredom** [comment]
Hey @angelog! Just back from holiday - I'll certainly look into adding this, really good idea.

**Comment by angelog** [comment]
Any update on this? Or maybe some pointers so that I could implement this myself? Could do a pull request. Looking to implement this as part of a product beta release this week :astonished:

**Comment by sheredom** [comment]
Hey @angelog! I'll not get to this this week (away on work stuff!)

I'd happily accept a PR from yourself though if you are willing to do the work!

**Comment by angelog** [comment]
I will do some research later today and get back to you. Thanks! :)

**Comment by sheredom** [comment]
Thanks for solving this @angelog !
