### ISSUE TITLE
conflicting int32_t definition

### ISSUE THREAD

**Issue by braddabug** [sheredom/utf8.h#38]
uint8.h detects _MSC_VER and #defines int32_t. The problem is that I've got another header that uses int32_t in a typedef, which ends up creating this:

typedef __int32 __int32;

which gives me a compiler error. Since stdint.h is included in Visual Studio 2010 and up, I propose changing the check for _MSC_VER to something like this:

```
#if (_MSC_VER < 1600)
#define int32_t __int32
#define uint32_t __uint32
#else
#include <stdint.h>
#endif
```

That way if we have stdint.h with visual studio we don't have to resort to #defines.

**Comment by sheredom** [comment]
Good catch, I'll work something up 😄

**Comment by braddabug** [comment]
Wups, I guess that should be something more like

```
#if defined(_MSC_VER) && _MSC_VER < 1600
```
to be compatible with non-Visual C++ compilers.

**Comment by sheredom** [comment]
Fixed in https://github.com/sheredom/utf8.h/pull/39
