### ISSUE TITLE
Bug in utf8len on malformed UTF-8 string

### ISSUE THREAD

**Issue by fluks** [sheredom/utf8.h#5]
A malformed UTF-8 string will cause `utf8len` to read memory past `str's` null character. A buffer like this for example:

````
char str[] = { -16, '\0' };
````
The function needs additional checks if there is a null character somewhere not expected and then inform about an error in the `str`. Maybe it needs an error argument, set `errno` or return something else.

**Comment by sheredom** [comment]
So this is the reason I added utf8valid - basically so that you could validated the string was valid utf8 pre using the other functions. I wanted to maintain some level of compatibility with the string.h functions. I'll have a look at setting errno though!

**Comment by fluks** [comment]
It's not documented anywhere? Or the documentation is in progress, like it reads in the TODO list?

**Comment by sheredom** [comment]
Yeah I really need to do a pass to add documentation for each of the functions in the README. I'll add an issue for myself for that!

**Comment by sheredom** [comment]
Thanks to @underscorediscovery we've got documentation for utf8valid in the README.md. Closing this issue (but feel free to re-open if you have further concerns!)
