### ISSUE TITLE
Do you have plan to support char8_t?

### ISSUE THREAD

**Issue by yumetodo** [sheredom/utf8.h#59]
C++ committee decided to introduce char8_t type that assumes holding utf-8 encoded character on C++20. 
[P0482R5: char8_t: A type for UTF-8 characters and strings (Revision 5)](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0482r5.html)

**Comment by sheredom** [comment]
No - no plans sorry.
