### ISSUE TITLE
utf8.h:399: redeclaration of method utf8size

### ISSUE THREAD

**Issue by Prunes93** [sheredom/utf8.h#67]
In line 399 of utf8.h, function `size_t utf8size(const void *str)` is redeclared, causing a compile-time error (using GCC 9.1).
First declaration is in line 162.

**Comment by sheredom** [comment]
Can you try https://github.com/sheredom/utf8.h/pull/68 please?

**Comment by Prunes93** [comment]
Of course it works! Thank you.
