### ISSUE TITLE
Why not use memcpy()?

### ISSUE THREAD

**Issue by f2404** [sheredom/utf8.h#8]
```c
    // copy src byte-by-byte into our new utf8 string
    while ('\0' != s[bytes]) {
      n[bytes] = s[bytes];
      bytes++;
    }
```

**Comment by sheredom** [comment]
I don't want any dependencies on any other header that I can get away with. Using memcpy would require me to include string.h, which I really do not want to do.

**Comment by f2404** [comment]
I'm just concerned that byte-by-byte copying is not that effective as memcpy() since the latter may be optimized, even for a particular platform, etc.

**Comment by sheredom** [comment]
That is a valid concern for sure. I can say that I've checked the output on clang and this is converted into a memcpy by the optimizer anyway.

**Comment by f2404** [comment]
Ok, thanks.
