### ISSUE TITLE
Allow programmer specified allocator

### ISSUE THREAD

**Issue by warmwaffles** [sheredom/utf8.h#84]
Would be nice to maybe provide a way for the person including the utf8 code to be able to do something like

```c
#define utf8malloc my_alloc
#include "utf8.h"
```

I would make a PR to do this, but I don't know if it would be anything anyone is interested in.

**Comment by sheredom** [comment]
There is only two entry points `utf8dup` and `utf8ndup` that use `malloc` - I think I'd rather add `utf8dup_ex` that takes a user provided allocator to do this (similar to the user allocator in my other lib `json.h`. Thoughts?

**Comment by warmwaffles** [comment]
I think that would work too. Rationale is that I am using this library for some small stuff in an erlang NIF and would prefer to use erlang's allocator and deallocator there.
